Repository UKHomeOffice/hocs-mi-transformation, pull requests merged in 2022-11, with the labels that each got.

#1 Quay image
  .github/workflows/docker-push.yml
  Dockerfile
Labels: major

#3 changed description
  helm/hocs-mi-transformation/Chart.yaml
Labels: patch

#4 removed auth-proxy
  helm/hocs-mi-transformation/templates/auth-proxy-cm.yaml
  helm/hocs-mi-transformation/templates/deployment-app.yaml
Labels: patch

#5 Change entry point to echo hello world
  Dockerfile
Labels: patch

#6 Remove entrypoint of image
  Dockerfile
Labels: patch

#7 Run sleep command
  Dockerfile
Labels: patch

#8 setting command to be python
  Dockerfile
Labels: patch

#11 Update test script to query read replica
  helm/hocs-mi-transformation/templates/cronjob.yaml
  test.py
Labels: minor

#12 Run dbt version from venv bin
  Dockerfile
Labels: patch

#13 Setting api version to batch/v1
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#14 Setting to beta
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#15 Removing unneeded sections of cronjob yml
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#17 Add restart policy of never
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#18 Update resource name to correct spelling:
  helm/values-notprod.yaml
Labels: patch

#19 Cast port as int:
  test.py
Labels: patch

#20 Changed from MySQL to Postgres
  requirements.txt
  test.py
Labels: patch

#21 Add postgressql package to dockerfile
  Dockerfile
Labels: patch

#22 Change package from postgres to libpq-dev
  Dockerfile
Labels: patch

#23 Add from source
  requirements.txt
Labels: patch

#25 Test transformation credentials connect successfully
  test.py
Labels: patch

#26 Test data query
  Dockerfile
  extract_data.py
  test.py
Labels: patch

#27 Run select query of top 10, and print each row
  extract_data.py
Labels: patch

#28 version.txt
  version.txt
Labels: patch

#31 Create local DBs
  Makefile
  README.md
  dbreplica/init.sql
  docker-compose.yml
  extract_data.py
Labels: patch

#33 Change to every 10 minutes for the job
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#34 change back to transform rather than transformation
  extract_data.py
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#35 Not sure what happened with the combo here
  extract_data.py
  helm/values-notprod.yaml
Labels: patch

#41 New line:
  Makefile
Labels: patch

#45 Update Kubectl values
  Makefile
Labels: patch

#46 Remove period at the end of SETGID
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#47 Add transformation host into yml
  helm/values-notprod.yaml
Labels: patch

#48 Endpoint is the host here for transformation
  helm/values-notprod.yaml
Labels: patch

#49 Just copy first 10 rows for now
  extract_data.py
Labels: patch

#52 removed space
  transformations/models/ukvi/performance.sql
Labels: patch

#53 Feature/data transformation aggregate
  dbreplica/init.sql
  extract_data.sh
  output_test.sh
  run_etl.sh
  transformations/models/MPAM_due_cases/models.yml
  transformations/models/MPAM_due_cases/mpam_due_cases.sql
  transformations/models/MPAM_due_cases/mpam_due_cases_aggregate.sql
  transformations/models/flatten/flatten.sql
  transformations/models/flatten/models.yml
  transformations/models/payload/json_data.sql
Labels: patch

#54 Feature/data transformation aggregate
  helm/hocs-mi-transformation/templates/cronjob.yaml
  output_test.sh
  run_etl.sh
Labels: patch

#55 remove security context to allow running as root user
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#56 explicitly set run as non root to false
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#57 testing a select of transform data
  output_test.sh
  run_etl.sh
Labels: patch

#58 Add output test to image and add infinite sleep
  Dockerfile
  run_etl.sh
Labels: patch

#59 Dbt output test
  Dockerfile
  helm/hocs-mi-transformation/templates/cronjob.yaml
  transformations/.user.yml
  transformations/dbt_project.yml
  transformations/models/MPAM_due_cases/models.yml
  transformations/models/MPAM_due_cases/mpam_due_cases.sql
  transformations/models/MPAM_due_cases/mpam_due_cases_aggregate.sql
  transformations/models/flatten/flatten.sql
  transformations/models/flatten/models.yml
  transformations/models/sources.yml
  transformations/models/ukvi/models.yml
  transformations/models/ukvi/performance.sql
  transformations/profiles/.user.yml
  transformations/profiles/profiles.yml
  transformations/tests/generic/test_gt_zero.sql
  transformations/tests/generic/test_not_empty.sql
Labels: patch

#60 Set profile port using environment variable
  transformations/models/MPAM_due_cases/mpam_due_cases_aggregate.sql
  transformations/models/flatten/flatten.sql
  transformations/profiles/profiles.yml
Labels: patch

#62 No label
  extract_data.sh
Labels: patch

#63 Remove concurrency policy
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#65 No label
  run_etl.sh
Labels: patch

#66 Dbt output test
  extract_data.sh
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#67 Back to 5 minutes
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#69 No label
  extract_data.sh
Labels: patch

#70 Short timespan for the where statement
  extract_data.sh
Labels: patch

#71 Only select top 1000
  extract_data.sh
Labels: patch

#72 Dbt output test
  extract_data.sh
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#73 remove concurrency
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch

#74 Add concurrency policy but in the right place this time
  helm/hocs-mi-transformation/templates/cronjob.yaml
Labels: patch
